import type { Category, Product } from "./types";

const img = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?w=${w}&q=80&auto=format&fit=crop`;

export const categories: {
  id: Category;
  name: string;
  description: string;
  icon: string;
  image: string;
}[] = [
  {
    id: "smartphones",
    name: "Smartphones",
    description: "Flagship & latest devices",
    icon: "smartphone",
    image: img("photo-1598327105666-5b89351aff97", 600),
  },
  {
    id: "earbuds",
    name: "Earbuds",
    description: "Premium wireless audio",
    icon: "headphones",
    image: img("photo-1590658268037-6bf12165a8df", 600),
  },
  {
    id: "cases",
    name: "Cases",
    description: "Protection with style",
    icon: "shield",
    image: img("photo-1601784551446-20c9e07cdbdb", 600),
  },
  {
    id: "chargers",
    name: "Chargers",
    description: "Fast & wireless charging",
    icon: "zap",
    image: img("photo-1583394838336-acd977736f90", 600),
  },
  {
    id: "smartwatches",
    name: "Smartwatches",
    description: "Wearable tech excellence",
    icon: "watch",
    image: img("photo-1579586337278-3befd40fd17a", 600),
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Essential tech add-ons",
    icon: "package",
    image: img("photo-1625842268584-8f3296236761", 600),
  },
];

export const brands = [
  "Apple",
  "Samsung",
  "Google",
  "Nothing",
  "OnePlus",
  "Sony",
  "Anker",
  "Belkin",
];

export const products: Product[] = [
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    brand: "Apple",
    category: "smartphones",
    price: 999,
    originalPrice: 1099,
    description:
      "The iPhone 16 Pro features a stunning titanium design, the powerful A18 Pro chip, and an advanced camera system with 5x optical zoom. Experience the future of mobile photography and performance.",
    shortDescription: "Titanium design. A18 Pro chip. Pro camera system.",
    images: [
      img("photo-1695048133142-1a20484d2569", 1000),
      img("photo-1511707171634-5f897ff02aa9", 1000),
      img("photo-1580910051074-3eb694886505", 1000),
    ],
    colors: [
      { name: "Natural Titanium", hex: "#9A9A9D" },
      { name: "Black Titanium", hex: "#3C3C3D" },
      { name: "White Titanium", hex: "#F5F5F0" },
      { name: "Desert Titanium", hex: "#C4A77D" },
    ],
    variants: [
      { id: "ip16p-128", storage: "128GB", ram: "8GB", price: 999, inStock: true },
      { id: "ip16p-256", storage: "256GB", ram: "8GB", price: 1099, inStock: true },
      { id: "ip16p-512", storage: "512GB", ram: "8GB", price: 1299, inStock: true },
    ],
    specs: {
      Display: '6.3" Super Retina XDR OLED',
      Processor: "Apple A18 Pro",
      Camera: "48MP Main + 48MP Ultra Wide + 12MP 5x Telephoto",
      Battery: "Up to 27 hours video playback",
      OS: "iOS 18",
      Weight: "199g",
    },
    rating: 4.9,
    reviewCount: 2847,
    reviews: [
      {
        id: "r1",
        author: "Marcus T.",
        rating: 5,
        date: "2026-03-15",
        title: "Best iPhone yet",
        content:
          "The titanium build feels incredible and the camera improvements are noticeable. Battery life is outstanding.",
        verified: true,
      },
      {
        id: "r2",
        author: "Sarah L.",
        rating: 5,
        date: "2026-02-28",
        title: "Worth every penny",
        content:
          "Upgraded from iPhone 14 Pro. The performance jump is real and the display is gorgeous.",
        verified: true,
      },
    ],
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ["flagship", "5g", "wireless-charging"],
  },
  {
    id: "samsung-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    category: "smartphones",
    price: 1199,
    description:
      "Samsung's ultimate flagship with Galaxy AI, a 200MP camera, built-in S Pen, and a gorgeous 6.9-inch display. Power meets intelligence.",
    shortDescription: "Galaxy AI. 200MP camera. Built-in S Pen.",
    images: [
      img("photo-1610945415295-d9bbf067e59c", 1000),
      img("photo-1610945415295-d9bbf067e59c", 1000),
      img("photo-1511707171634-5f897ff02aa9", 1000),
    ],
    colors: [
      { name: "Titanium Black", hex: "#2D2D2D" },
      { name: "Titanium Gray", hex: "#8B8B8B" },
      { name: "Titanium Violet", hex: "#7B68A6" },
    ],
    variants: [
      { id: "s25u-256", storage: "256GB", ram: "12GB", price: 1199, inStock: true },
      { id: "s25u-512", storage: "512GB", ram: "12GB", price: 1319, inStock: true },
      { id: "s25u-1tb", storage: "1TB", ram: "12GB", price: 1539, inStock: false },
    ],
    specs: {
      Display: '6.9" Dynamic AMOLED 2X, 120Hz',
      Processor: "Snapdragon 8 Elite",
      Camera: "200MP Main + 50MP Periscope + 12MP Ultra Wide",
      Battery: "5000mAh with 45W fast charging",
      OS: "Android 15 with One UI 7",
      Weight: "233g",
    },
    rating: 4.8,
    reviewCount: 1923,
    reviews: [
      {
        id: "r3",
        author: "James K.",
        rating: 5,
        date: "2026-03-01",
        title: "S Pen is a game changer",
        content: "The AI features are surprisingly useful. Camera quality is unmatched.",
        verified: true,
      },
    ],
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ["flagship", "s-pen", "ai"],
  },
  {
    id: "google-pixel-9-pro",
    name: "Pixel 9 Pro",
    brand: "Google",
    category: "smartphones",
    price: 899,
    originalPrice: 999,
    description:
      "Pure Android experience with Google's best AI. Exceptional computational photography and 7 years of updates.",
    shortDescription: "Google AI. Best-in-class camera. 7 years of updates.",
    images: [
      img("photo-1598327105666-5b89351aff97", 1000),
      img("photo-1511707171634-5f897ff02aa9", 1000),
    ],
    colors: [
      { name: "Obsidian", hex: "#1A1A1A" },
      { name: "Porcelain", hex: "#F0EDE8" },
      { name: "Hazel", hex: "#8B9A7B" },
    ],
    variants: [
      { id: "px9p-128", storage: "128GB", ram: "12GB", price: 899, inStock: true },
      { id: "px9p-256", storage: "256GB", ram: "12GB", price: 999, inStock: true },
    ],
    specs: {
      Display: '6.3" LTPO OLED, 120Hz',
      Processor: "Google Tensor G4",
      Camera: "50MP Main + 48MP Ultra Wide + 48MP Telephoto",
      Battery: "4700mAh with 30W charging",
      OS: "Android 15",
      Weight: "199g",
    },
    rating: 4.7,
    reviewCount: 1456,
    reviews: [],
    isNew: true,
    isFeatured: true,
    tags: ["ai", "camera", "stock-android"],
  },
  {
    id: "nothing-phone-3",
    name: "Phone (3)",
    brand: "Nothing",
    category: "smartphones",
    price: 599,
    description:
      "Iconic Glyph Interface meets flagship performance. Transparent design with a unique aesthetic that stands out.",
    shortDescription: "Glyph Interface. Transparent design. Flagship specs.",
    images: [
      img("photo-1592899677977-9c10ca588bbd", 1000),
      img("photo-1598327105666-5b89351aff97", 1000),
    ],
    colors: [
      { name: "White", hex: "#F5F5F5" },
      { name: "Black", hex: "#1A1A1A" },
    ],
    variants: [
      { id: "np3-256", storage: "256GB", ram: "12GB", price: 599, inStock: true },
      { id: "np3-512", storage: "512GB", ram: "12GB", price: 699, inStock: true },
    ],
    specs: {
      Display: '6.7" LTPO AMOLED, 120Hz',
      Processor: "Snapdragon 8s Gen 3",
      Camera: "50MP Main + 50MP Ultra Wide",
      Battery: "5000mAh with 45W charging",
      OS: "Nothing OS 3.0",
      Weight: "199g",
    },
    rating: 4.6,
    reviewCount: 892,
    reviews: [],
    isNew: true,
    isBestSeller: true,
    tags: ["glyph", "design", "value"],
  },
  {
    id: "oneplus-13",
    name: "OnePlus 13",
    brand: "OnePlus",
    category: "smartphones",
    price: 799,
    description:
      "Speed meets sophistication. Hasselblad-tuned cameras, blazing fast charging, and a silky smooth display.",
    shortDescription: "Hasselblad camera. 100W charging. Smooth display.",
    images: [
      img("photo-1592899677977-9c10ca588bbd", 1000),
      img("photo-1511707171634-5f897ff02aa9", 1000),
    ],
    colors: [
      { name: "Midnight Ocean", hex: "#1B2838" },
      { name: "Arctic Dawn", hex: "#E8E4DF" },
    ],
    variants: [
      { id: "op13-256", storage: "256GB", ram: "12GB", price: 799, inStock: true },
      { id: "op13-512", storage: "512GB", ram: "16GB", price: 899, inStock: true },
    ],
    specs: {
      Display: '6.82" LTPO AMOLED, 120Hz',
      Processor: "Snapdragon 8 Elite",
      Camera: "50MP Hasselblad Main + 50MP Ultra Wide + 50MP Periscope",
      Battery: "6000mAh with 100W charging",
      OS: "OxygenOS 15",
      Weight: "210g",
    },
    rating: 4.7,
    reviewCount: 734,
    reviews: [],
    isBestSeller: true,
    tags: ["fast-charging", "hasselblad"],
  },
  {
    id: "airpods-pro-3",
    name: "AirPods Pro (3rd Gen)",
    brand: "Apple",
    category: "earbuds",
    price: 249,
    description:
      "Active Noise Cancellation redefined. Adaptive Audio, personalized spatial audio, and USB-C charging.",
    shortDescription: "ANC 2.0. Adaptive Audio. USB-C.",
    images: [
      img("photo-1606220945770-b5b6c2c55bf1", 1000),
      img("photo-1590658268037-6bf12165a8df", 1000),
    ],
    colors: [{ name: "White", hex: "#F5F5F5" }],
    variants: [
      { id: "app3-std", storage: "N/A", ram: "N/A", price: 249, inStock: true },
    ],
    specs: {
      "Driver": "Custom high-excursion driver",
      "ANC": "Active Noise Cancellation 2.0",
      "Battery": "6 hours (30 hours with case)",
      "Connectivity": "Bluetooth 5.3, USB-C",
      "Water Resistance": "IP54",
    },
    rating: 4.8,
    reviewCount: 3421,
    reviews: [],
    isBestSeller: true,
    isFeatured: true,
    tags: ["anc", "wireless"],
  },
  {
    id: "galaxy-buds3-pro",
    name: "Galaxy Buds3 Pro",
    brand: "Samsung",
    category: "earbuds",
    price: 229,
    originalPrice: 249,
    description:
      "Intelligent ANC with blade lights design. Hi-Fi sound and seamless Galaxy ecosystem integration.",
    shortDescription: "Blade lights. Intelligent ANC. Hi-Fi sound.",
    images: [
      img("photo-1590658268037-6bf12165a8df", 1000),
      img("photo-1606220945770-b5b6c2c55bf1", 1000),
    ],
    colors: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "White", hex: "#FFFFFF" },
    ],
    variants: [
      { id: "gb3p-std", storage: "N/A", ram: "N/A", price: 229, inStock: true },
    ],
    specs: {
      "Driver": "10.5mm + 6.5mm dual driver",
      "ANC": "Intelligent Active Noise Cancellation",
      "Battery": "6 hours (30 hours with case)",
      "Connectivity": "Bluetooth 5.4",
      "Water Resistance": "IP57",
    },
    rating: 4.6,
    reviewCount: 1876,
    reviews: [],
    isBestSeller: true,
    tags: ["anc", "samsung"],
  },
  {
    id: "sony-wf1000xm5",
    name: "WF-1000XM5",
    brand: "Sony",
    category: "earbuds",
    price: 279,
    description:
      "Industry-leading noise cancellation in the world's smallest form factor. LDAC hi-res audio support.",
    shortDescription: "Best-in-class ANC. LDAC hi-res. Compact design.",
    images: [
      img("photo-1606220945770-b5b6c2c55bf1", 1000),
      img("photo-1590658268037-6bf12165a8df", 1000),
    ],
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "Silver", hex: "#C8C8C8" },
    ],
    variants: [
      { id: "swf-std", storage: "N/A", ram: "N/A", price: 279, inStock: true },
    ],
    specs: {
      "Driver": "8.4mm dynamic driver",
      "ANC": "Integrated Processor V2",
      "Battery": "8 hours (24 hours with case)",
      "Connectivity": "Bluetooth 5.3, LDAC",
      "Water Resistance": "IPX4",
    },
    rating: 4.9,
    reviewCount: 2156,
    reviews: [],
    isFeatured: true,
    tags: ["anc", "hi-res"],
  },
  {
    id: "apple-watch-ultra-3",
    name: "Apple Watch Ultra 3",
    brand: "Apple",
    category: "smartwatches",
    price: 799,
    description:
      "The most capable Apple Watch. Titanium case, precision dual-frequency GPS, and up to 36 hours of battery.",
    shortDescription: "Titanium. Dual GPS. 36hr battery.",
    images: [
      img("photo-1579586337278-3befd40fd17a", 1000),
      img("photo-1523275335684-37898b6baf30", 1000),
    ],
    colors: [
      { name: "Natural Titanium", hex: "#9A9A9D" },
      { name: "Black Titanium", hex: "#3C3C3D" },
    ],
    variants: [
      { id: "awu3-49", storage: "64GB", ram: "N/A", price: 799, inStock: true },
    ],
    specs: {
      Display: '49mm Always-On Retina LTPO3',
      Case: "Grade 5 Titanium",
      Battery: "Up to 36 hours",
      "Water Resistance": "100m WR50",
      GPS: "Precision dual-frequency GPS",
    },
    rating: 4.8,
    reviewCount: 1234,
    reviews: [],
    isNew: true,
    isFeatured: true,
    tags: ["fitness", "outdoor"],
  },
  {
    id: "galaxy-watch-7",
    name: "Galaxy Watch 7",
    brand: "Samsung",
    category: "smartwatches",
    price: 299,
    originalPrice: 349,
    description:
      "Advanced health monitoring with BioActive Sensor. Sleek design with Wear OS powered by Samsung.",
    shortDescription: "BioActive Sensor. Wear OS. Sleek design.",
    images: [
      img("photo-1523275335684-37898b6baf30", 1000),
      img("photo-1579586337278-3befd40fd17a", 1000),
    ],
    colors: [
      { name: "Green", hex: "#4A6741" },
      { name: "Silver", hex: "#C0C0C0" },
    ],
    variants: [
      { id: "gw7-40", storage: "16GB", ram: "N/A", price: 299, inStock: true },
      { id: "gw7-44", storage: "16GB", ram: "N/A", price: 329, inStock: true },
    ],
    specs: {
      Display: '1.5" Super AMOLED',
      Case: "Armor Aluminum",
      Battery: "Up to 30 hours",
      "Water Resistance": "5ATM + IP68",
      OS: "Wear OS 5",
    },
    rating: 4.5,
    reviewCount: 987,
    reviews: [],
    isBestSeller: true,
    tags: ["health", "wear-os"],
  },
  {
    id: "magsafe-case-pro",
    name: "MagSafe Silicone Case Pro",
    brand: "Apple",
    category: "cases",
    price: 49,
    description:
      "Premium silicone case with built-in MagSafe magnets. Soft microfiber lining protects your device.",
    shortDescription: "MagSafe compatible. Premium silicone. Microfiber lining.",
    images: [
      img("photo-1601784551446-20c9e07cdbdb", 1000),
      img("photo-1601593346740-925612772716", 1000),
    ],
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "Midnight", hex: "#2C3E50" },
      { name: "Cypress", hex: "#4A6741" },
      { name: "Orange", hex: "#E67E22" },
    ],
    variants: [
      { id: "msc-std", storage: "N/A", ram: "N/A", price: 49, inStock: true },
    ],
    specs: {
      Material: "Premium silicone with microfiber lining",
      Compatibility: "MagSafe accessories",
      Protection: "Drop protection up to 6ft",
      Weight: "32g",
    },
    rating: 4.4,
    reviewCount: 2341,
    reviews: [],
    isBestSeller: true,
    tags: ["magsafe", "protection"],
  },
  {
    id: "spigen-tough-armor",
    name: "Tough Armor Case",
    brand: "Belkin",
    category: "cases",
    price: 34,
    description:
      "Military-grade protection with Air Cushion Technology. Raised edges protect screen and camera.",
    shortDescription: "Military-grade. Air Cushion Tech. Slim profile.",
    images: [
      img("photo-1601593346740-925612772716", 1000),
      img("photo-1601784551446-20c9e07cdbdb", 1000),
    ],
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "Gunmetal", hex: "#4A4A4A" },
    ],
    variants: [
      { id: "sta-std", storage: "N/A", ram: "N/A", price: 34, inStock: true },
    ],
    specs: {
      Material: "TPU + Polycarbonate",
      Protection: "MIL-STD-810G certified",
      Features: "Kickstand, raised bezels",
      Weight: "45g",
    },
    rating: 4.5,
    reviewCount: 4521,
    reviews: [],
    tags: ["rugged", "protection"],
  },
  {
    id: "anker-737-charger",
    name: "Anker 737 Charger (GaNPrime 120W)",
    brand: "Anker",
    category: "chargers",
    price: 89,
    originalPrice: 109,
    description:
      "120W GaNPrime charger with 3 ports. Charge laptop, phone, and tablet simultaneously at full speed.",
    shortDescription: "120W GaN. 3 ports. Compact design.",
    images: [
      img("photo-1583394838336-acd977736f90", 1000),
      img("photo-1583394838336-acd977736f90", 1000),
    ],
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    variants: [
      { id: "a737-std", storage: "N/A", ram: "N/A", price: 89, inStock: true },
    ],
    specs: {
      Output: "120W total (USB-C 100W + USB-C 20W + USB-A 18W)",
      Technology: "GaNPrime II",
      Ports: "2x USB-C, 1x USB-A",
      Weight: "220g",
    },
    rating: 4.8,
    reviewCount: 3210,
    reviews: [],
    isBestSeller: true,
    isFeatured: true,
    tags: ["gan", "fast-charging"],
  },
  {
    id: "magsafe-charger-stand",
    name: "MagSafe 3-in-1 Charging Stand",
    brand: "Belkin",
    category: "chargers",
    price: 149,
    description:
      "Charge iPhone, Apple Watch, and AirPods simultaneously. Premium aluminum stand with fast 15W MagSafe.",
    shortDescription: "3-in-1 wireless. 15W MagSafe. Premium aluminum.",
    images: [
      img("photo-1583394838336-acd977736f90", 1000),
      img("photo-1583394838336-acd977736f90", 1000),
    ],
    colors: [
      { name: "White", hex: "#F5F5F5" },
      { name: "Black", hex: "#1A1A1A" },
    ],
    variants: [
      { id: "mcs-std", storage: "N/A", ram: "N/A", price: 149, inStock: true },
    ],
    specs: {
      Output: "15W MagSafe + 5W Apple Watch + 5W AirPods",
      Material: "Premium aluminum",
      Compatibility: "MagSafe iPhones, Apple Watch, AirPods",
    },
    rating: 4.6,
    reviewCount: 1567,
    reviews: [],
    tags: ["wireless", "magsafe", "stand"],
  },
  {
    id: "usb-c-cable-pack",
    name: "USB-C Braided Cable 3-Pack",
    brand: "Anker",
    category: "accessories",
    price: 24,
    description:
      "Durable braided nylon cables with 100W power delivery. 6ft length for versatile charging.",
    shortDescription: "100W PD. Braided nylon. 6ft length.",
    images: [
      img("photo-1625842268584-8f3296236761", 1000),
      img("photo-1583394838336-acd977736f90", 1000),
    ],
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "White", hex: "#F5F5F5" },
    ],
    variants: [
      { id: "ucc-3pk", storage: "N/A", ram: "N/A", price: 24, inStock: true },
    ],
    specs: {
      Length: "6ft (1.8m) each",
      Power: "100W USB-C PD",
      Material: "Braided nylon",
      Quantity: "3 cables",
    },
    rating: 4.7,
    reviewCount: 8934,
    reviews: [],
    isBestSeller: true,
    tags: ["cable", "value"],
  },
  {
    id: "phone-grip-stand",
    name: "Premium Phone Grip & Stand",
    brand: "Belkin",
    category: "accessories",
    price: 29,
    description:
      "Sleek aluminum phone grip that doubles as a stand. MagSafe compatible with 360° rotation.",
    shortDescription: "MagSafe grip. 360° rotation. Aluminum build.",
    images: [
      img("photo-1625842268584-8f3296236761", 1000),
      img("photo-1601784551446-20c9e07cdbdb", 1000),
    ],
    colors: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Black", hex: "#1A1A1A" },
    ],
    variants: [
      { id: "pgs-std", storage: "N/A", ram: "N/A", price: 29, inStock: true },
    ],
    specs: {
      Material: "Aircraft-grade aluminum",
      Compatibility: "MagSafe iPhones",
      Features: "360° rotation, kickstand",
      Weight: "28g",
    },
    rating: 4.3,
    reviewCount: 1234,
    reviews: [],
    tags: ["magsafe", "grip"],
  },
  {
    id: "screen-protector-pack",
    name: "Tempered Glass Screen Protector 2-Pack",
    brand: "Belkin",
    category: "accessories",
    price: 19,
    description:
      "9H hardness tempered glass with oleophobic coating. Easy installation kit included.",
    shortDescription: "9H hardness. Oleophobic coating. Easy install.",
    images: [
      img("photo-1601593346740-925612772716", 1000),
      img("photo-1625842268584-8f3296236761", 1000),
    ],
    colors: [{ name: "Clear", hex: "#FFFFFF" }],
    variants: [
      { id: "tgp-2pk", storage: "N/A", ram: "N/A", price: 19, inStock: true },
    ],
    specs: {
      Hardness: "9H tempered glass",
      Coating: "Oleophobic anti-fingerprint",
      Thickness: "0.33mm",
      Quantity: "2 protectors + install kit",
    },
    rating: 4.4,
    reviewCount: 5678,
    reviews: [],
    tags: ["protection", "value"],
  },
  {
    id: "portable-power-bank",
    name: "PowerCore 20K Power Bank",
    brand: "Anker",
    category: "accessories",
    price: 59,
    originalPrice: 69,
    description:
      "20000mAh capacity with 30W USB-C PD. Charge your phone 4+ times on a single charge.",
    shortDescription: "20000mAh. 30W PD. Charge 4+ times.",
    images: [
      img("photo-1609091839311-d5365f9ff1c5", 1000),
      img("photo-1625842268584-8f3296236761", 1000),
    ],
    colors: [
      { name: "Black", hex: "#1A1A1A" },
      { name: "White", hex: "#F5F5F5" },
    ],
    variants: [
      { id: "ppb-20k", storage: "N/A", ram: "N/A", price: 59, inStock: true },
    ],
    specs: {
      Capacity: "20000mAh",
      Output: "30W USB-C PD + 18W USB-A",
      Ports: "1x USB-C, 1x USB-A",
      Weight: "345g",
    },
    rating: 4.7,
    reviewCount: 4567,
    reviews: [],
    isBestSeller: true,
    tags: ["power-bank", "travel"],
  },
];
